In [1]:
pip install pandas

Requirement already satisfied: pandas in ./lib/python3.12/site-packages (3.0.3)
Requirement already satisfied: numpy>=1.26.0 in ./lib/python3.12/site-packages (from pandas) (2.4.6)
Requirement already satisfied: python-dateutil>=2.8.2 in ./lib/python3.12/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in ./lib/python3.12/site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

[notice] A new release of pip is available: 25.0.1 -> 26.1.2
[notice] To update, run: pip install --upgrade pip
Note: you may need to restart the kernel to use updated packages.

In [2]:
import pandas as pd

In [3]:
data = {'Name': ['Alice', 'Bob'], 'Age': [25, 30]}
df = pd.DataFrame(data)

In [4]:
lst = ['Alice', 25], ['Bob', 30]
df = pd.DataFrame(lst, columns=['Name', 'Age'])

In [5]:
df.head()

    Name  Age
0  Alice   25
1    Bob   30

In [6]:
df.tail()

    Name  Age
0  Alice   25
1    Bob   30

In [7]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 2 entries, 0 to 1
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    2 non-null      str
 1   Age     2 non-null      int64
dtypes: int64(1), str(1)
memory usage: 164.0 bytes

In [8]:
df.describe()

             Age
count   2.000000
mean   27.500000
std     3.535534
min    25.000000
25%    26.250000
50%    27.500000
75%    28.750000
max    30.000000

In [9]:
df['Name']

0    Alice
1      Bob
Name: Name, dtype: str

In [10]:
df[['Name', 'Age']]

    Name  Age
0  Alice   25
1    Bob   30

In [11]:
df.loc[0]

Name    Alice
Age        25
Name: 0, dtype: object

In [12]:
df.iloc[1]

Name    Bob
Age      30
Name: 1, dtype: object

In [13]:
df[df['Age'] > 25]

  Name  Age
1  Bob   30

In [14]:
df['Gender'] = ['F', 'M']

In [15]:
#df.drop('Age', axis=1, inplace=True)

In [16]:
df.isnull()

    Name    Age  Gender
0  False  False   False
1  False  False   False

In [17]:
df.dropna()

    Name  Age Gender
0  Alice   25      F
1    Bob   30      M

In [18]:
df.fillna(0)

    Name  Age Gender
0  Alice   25      F
1    Bob   30      M

In [19]:
df.groupby('Gender')['Age'].mean()

Gender
F    25.0
M    30.0
Name: Age, dtype: float64

In [20]:
df1 = pd.DataFrame({
    'key': [1, 2, 3, 4],
    'Name': ['Alice', 'Bob', 'Charlie', 'David']
})
df2 = pd.DataFrame({
    'key': [1, 2, 3, 5],
    'Age': [25, 30, 35, 40]
})
pd.merge(df1, df2, on='key')
df1

   key     Name
0    1    Alice
1    2      Bob
2    3  Charlie
3    4    David

In [22]:
print(df1.columns)
print(df2.columns)

Index(['key', 'Name'], dtype='str')
Index(['key', 'Age'], dtype='str')

In [23]:
df1.set_index('key').join(df2.set_index('key'))

        Name  Age
key
1      Alice   25
2        Bob   30
3    Charlie   35

In [25]:
df.sort_values('Age')

    Name  Age Gender
0  Alice   25      F
1    Bob   30      M

In [26]:
df['Age'].apply(lambda x: x + 1)

0    26
1    31
Name: Age, dtype: int64

In [27]:
df['Name'].unique()

<StringArray>
['Alice', 'Bob']
Length: 2, dtype: str

In [28]:
df['Age'].value_counts()

Age
25    1
30    1
Name: count, dtype: int64